definitions:
  request.ReqNote:
    properties:
      content:
        description: 内容
        type: string
    type: object
  respone.RespNote:
    properties:
      id:
        description: 返回文章id
        type: integer
      message:
        description: 返回信息
        type: string
    type: object
info:
  contact: {}
  description: Go 语言编程之旅：一起用 Go 做项目
  termsOfService: https://github.com/go-programming-tour-book
  title: 博客系统
  version: "1.0"
paths:
  /note/create:
    post:
      consumes:
      - application/json
      description: 写入一条笔记
      parameters:
      - description: 请求参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/request.ReqNote'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respone.RespNote'
      summary: 写笔记
      tags:
      - Note
swagger: "2.0"
